# Generated by Django 2.0.8 on 2018-12-17 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000, verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=True, related_name='posts_created_by', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='评论回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=True, related_name='reply_created_by', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
                ('post', models.ForeignKey(on_delete=True, related_name='reply_post', to='rubick.Post', verbose_name='关联回复')),
                ('updated_by', models.ForeignKey(null=True, on_delete=True, related_name='reply_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='回复时间')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='主题标题')),
                ('subject', models.TextField(max_length=4000, verbose_name='主题内容')),
                ('like', models.IntegerField(verbose_name='点赞数')),
                ('views', models.IntegerField(verbose_name='浏览数')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('starter', models.ForeignKey(on_delete=True, related_name='topics_starter', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=True, related_name='posts_topic', to='rubick.Topic', verbose_name='关联主题'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=True, related_name='posts_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='回复时间'),
        ),
    ]
