# Generated by Django 2.0.8 on 2018-12-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000, verbose_name='回复内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='评论回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(max_length=7, verbose_name='标签颜色')),
                ('color_hover', models.CharField(max_length=7, verbose_name='hove颜色')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='主题标题')),
                ('subject', models.TextField(max_length=4000, verbose_name='主题内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ForeignKey(on_delete=False, to='rubick.Tag', verbose_name='标签')),
                ('topic', models.ForeignKey(on_delete=True, to='rubick.Topic', verbose_name='主题')),
            ],
        ),
    ]
